apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookswap-client
  namespace: bookswap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookswap-client
  template:
    metadata:
      labels:
        app: bookswap-client
    spec:
      containers:
        - name: client
          image: omsantoshharsule/booksclient:v3
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bookswap-client-service
  namespace: bookswap
spec:
  type: NodePort
  selector:
    app: bookswap-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080