apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookswap-server
  namespace: bookswap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookswap-server
  template:
    metadata:
      labels:
        app: bookswap-server
    spec:
      containers:
        - name: server
          image: omsantoshharsule/booksserver:v3
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              value: "8003"
---
apiVersion: v1
kind: Service
metadata:
  name: bookswap-server-service
  namespace: bookswap
spec:
  type: NodePort
  selector:
    app: bookswap-server
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30081